version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6532:8080"
    environment:
      - MONGO_URI=mongodb://mongo/mango
      - PORT=8080
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6531:3000"
    networks:
      - app-network


  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "6530:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:

volumes:
  mongo-data:
