name: Frontend e2e

on:
  push:
  pull_request:

jobs:
  e2e-frontend:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged
        ports:
          - 27017:27017
          - 8080:8080
          - 3000:3000
        env:
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ${{ github.workspace }}:/workspace
        working-directory: /workspace

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and start services
        run: |
          docker-compose up -d --build
        working-directory: .

      - name: Wait for services to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 27017 && echo "MongoDB is up" && break
            echo "Waiting for MongoDB..."
            sleep 2
          done

          for i in {1..30}; do
            nc -z localhost 8080 && echo "Backend is up" && break
            echo "Waiting for Backend..."
            sleep 2
          done

          for i in {1..30}; do
            curl -s http://localhost:3000 && echo "Frontend is up" && break
            echo "Waiting for Frontend..."
            sleep 2
          done

      - name: Install dependencies for frontend
        run: npm ci
        working-directory: frontend

      - name: Install Playwright
        run: npx playwright install
        working-directory: frontend

      - name: Run Playwright tests
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          BASE_URL: http://localhost:3000
        run: npx playwright test --trace on
        working-directory: frontend

