name: Backend coverage
on:
  push:
  pull_request:

jobs:
  coverage-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies for frontend
        working-directory: Frontend/itmo_board_frontend
        run: npm ci

      - name: Check frontend coverage
        working-directory: Frontend/itmo_board_frontend
        run: |
          if npm run test:coverage 2>&1 | grep -q 'Jest: "global" coverage threshold for'; then
            echo "Error: Global coverage threshold found";
            exit 1;
          else
            echo "No global coverage threshold found, proceeding...";
          fi