name: Backend coverage
on:
  push:
  pull_request:

jobs:
  coverage-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies for frontend
        working-directory: Frontend/itmo_board_frontend
        run: npm ci

      - name: Check frontend coverage
        working-directory: Frontend/itmo_board_frontend
        run: |
          npm run test:coverage | grep -q 'Jest: "global" coverage threshold for' && echo "Global coverage threshold found" || (echo "Global coverage threshold not found" && exit 1)
